version: "3"
services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  mongo-seed:
    build: ./db
    environment:
      HOST: mongo
      DB: testament-core
    restart: on-failure
    depends_on:
      - mongo
  simulation-runner-service:
    image: testament-simulation-runner-service
    ports:
      - "8084:8083"
    env_file: env/simulation-runner.env
    restart: always
    depends_on:
      - rabbit
  script-generator-service:
    image: testament-script-generator-service
    ports:
      - "8085:8085"
    env_file: env/script-generator.env
    restart: always
    depends_on:
      - rabbit
