version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/data/db
  runner:
    image: testment-runner
    ports:
      - "8081:8081"
  dispatcher:
    image: testment-dispatcher
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/testment-dispatcher
      - ARYA_RUNNER_URI=http://runner:8081
    depends_on:
      - runner
      - mongo